language: cpp
os: osx
osx_image: xcode12.2
env:
  global:
    - DEPLOY_VERSION=$(<version.txt)
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
addons:
  homebrew:
    packages:
      - qt
    update: true
before_script:
  - brew upgrade qt
  - mkdir build
  - cd build
script:
  - |
    cmake \
    -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
    ..
  - ls
#  - echo "${DEPLOY_VERSION}"
#  - export DEPLOY_TAG="v${DEPLOY_VERSION}"
#  - export DEPLOY_FILE_NAME="ETL-${DEPLOY_VERSION}"
#  - export DEPLOY_NAME="ETL ${DEPLOY_VERSION}"
#  - make
#  - cpack -G DragNDrop
#  - |
#    mkdir drop
#    cp -a "${DEPLOY_FILE_NAME}" ./drop/"${DEPLOY_FILE_NAME}"
#    cd ./drop
#  - |
#    hdiutil attach "${DEPLOY_FILE_NAME}"
#    cp -a "/Volumes/ReleaseInstaller-${DEPLOY_VERSION}-Darwin/ReleaseInstaller.app" ReleaseInstaller.app
#    hdiutil detach "/Volumes/ReleaseInstaller-${DEPLOY_VERSION}-Darwin"
#  - zip -r ReleaseInstaller.zip ReleaseInstaller.app
#before_deploy:
#  - git config --local user.name "lmsorenson"
#  - git config --local user.email "lsorenson20@gmail.com"
#deploy:
#  provider: releases
#  api_key: ${GITHUB_TOKEN}
#  file:
#    - ${DEPLOY_FILE_NAME}
#  skip_cleanup: true
#  name: ${DEPLOY_NAME}
#  tag_name: ${DEPLOY_TAG}
#  prerelease: false
